#!/bin/bash

# sed all SED_* variables to replace deploy_containerapp.yaml, such as 
# SED_INPUT_STORAGE_ACCOUNT, SED_INPUT_STORAGE_ACCOUNT_CONNECTIONSTRING, SED_INPUT_STORAGE_CONTAINER, SED_OUTPUT_STORAGE_ACCOUNT, SED_OUTPUT_STORAGE_ACCOUNT_CONNECTIONSTRING, SED_OUTPUT_STORAGE_CONTAINER

sed -i "s/SED_INPUT_STORAGE_ACCOUNT/$INPUT_STORAGE_ACCOUNT/g" deploy_containerapp.yaml
sed -i "s/SED_INPUT_STORAGE_ACCOUNT_CONNECTIONSTRING/$INPUT_STORAGE_ACCOUNT_CONNECTIONSTRING/g" deploy_containerapp.yaml
sed -i "s/SED_INPUT_STORAGE_CONTAINER/$INPUT_STORAGE_CONTAINER/g" deploy_containerapp.yaml
sed -i "s/SED_OUTPUT_STORAGE_ACCOUNT/$OUTPUT_STORAGE_ACCOUNT/g" deploy_containerapp.yaml
sed -i "s/SED_OUTPUT_STORAGE_ACCOUNT_CONNECTIONSTRING/$OUTPUT_STORAGE_ACCOUNT_CONNECTIONSTRING/g" deploy_containerapp.yaml
sed -i "s/SED_OUTPUT_STORAGE_CONTAINER/$OUTPUT_STORAGE_CONTAINER/g" deploy_containerapp.yaml


az containerapp create --name $CONTAINERAPP_NAME --resource-group $RESOURCE_GROUP \
    --yaml deploy_containerapp.yaml
