#!/bin/bash

export RESOURCE_GROUP=pathology-poc
export CONTAINERAPP_NAME=dicom-etl
export INPUT_STORAGE_ACCOUNT=ndpi
export INPUT_STORAGE_ACCOUNT_CONNECTIONSTRING=Gzv/NVzQeJfd0jLl6vmwXRl1WrZ96Eynbg+jnCq4VRE8XWws1XNGX7tx+dAvhmUV3lbg7cFKuzb4+ASt4owGkQ==
export INPUT_STORAGE_CONTAINER=input
export OUTPUT_STORAGE_ACCOUNT=dcmoutput
export OUTPUT_STORAGE_ACCOUNT_CONNECTIONSTRING=+L75dJIjjx7Hq3T6insy7I9LyXli/Juilby6o7KLI6Bb9WbFSvhpgM28P7wekvkhF37ikUw1ChZu+AStZWQ3lw==
export OUTPUT_STORAGE_CONTAINER=output

# sed all SED_* variables to replace deploy_containerapp.yaml, such as 
# SED_INPUT_STORAGE_ACCOUNT, SED_INPUT_STORAGE_ACCOUNT_CONNECTIONSTRING, SED_INPUT_STORAGE_CONTAINER, SED_OUTPUT_STORAGE_ACCOUNT, SED_OUTPUT_STORAGE_ACCOUNT_CONNECTIONSTRING, SED_OUTPUT_STORAGE_CONTAINER

sed -i "s/SED_INPUT_STORAGE_ACCOUNT/$INPUT_STORAGE_ACCOUNT/g" deploy_containerapp.yaml
sed -i "s/SED_INPUT_STORAGE_ACCOUNT_CONNECTIONSTRING/$INPUT_STORAGE_ACCOUNT_CONNECTIONSTRING/g" deploy_containerapp.yaml
sed -i "s/SED_INPUT_STORAGE_CONTAINER/$INPUT_STORAGE_CONTAINER/g" deploy_containerapp.yaml
sed -i "s/SED_OUTPUT_STORAGE_ACCOUNT/$OUTPUT_STORAGE_ACCOUNT/g" deploy_containerapp.yaml
sed -i "s/SED_OUTPUT_STORAGE_ACCOUNT_CONNECTIONSTRING/$OUTPUT_STORAGE_ACCOUNT_CONNECTIONSTRING/g" deploy_containerapp.yaml
sed -i "s/SED_OUTPUT_STORAGE_CONTAINER/$OUTPUT_STORAGE_CONTAINER/g" deploy_containerapp.yaml

          
az containerapp create --name $CONTAINERAPP_NAME --resource-group $RESOURCE_GROUP \
    --yaml deploy_containerapp.yaml
